name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed
    branches: [main]
env:
  AWS_REGION: eu-central-1
  EC2_HOST: ec2-3-64-57-137.eu-central-1.compute.amazonaws.com
  DEPLOY_PATH: /var/www/pwa
  SSH_USER: ec2-user
  AWS_PLATFORM: linux/amd64
  NODE_ENV: production

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Generate deployment package
      run: |
        TIMESTAMP=$(date +%Y%m%d_%H%M%S)
        tar -czf deployment.tar.gz dist/* # Replace 'dist' with your build output directory

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Write the SSH key to a file
        echo "$SSH_PRIVATE_KEY" > deploy_key
        chmod 600 deploy_key
        
        # Create release directory with timestamp
        TIMESTAMP=$(date +%Y%m%d_%H%M%S)
        RELEASE_DIR=${{ env.DEPLOY_PATH }}/releases/$TIMESTAMP
        
        # Upload and deploy
        scp -i deploy_key -o StrictHostKeyChecking=no deployment.tar.gz ${{ env.SSH_USER }}@${{ env.EC2_HOST }}:/tmp/
        
        ssh -i deploy_key -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.EC2_HOST }} << 'ENDSSH'
          # Create release directory
          sudo mkdir -p $RELEASE_DIR
          
          # Extract deployment package
          cd /tmp
          sudo tar -xzf deployment.tar.gz -C $RELEASE_DIR
          
          # Update symlinks
          sudo ln -sfn $RELEASE_DIR ${{ env.DEPLOY_PATH }}/current
          
          # Cleanup old releases (keep last 5)
          cd ${{ env.DEPLOY_PATH }}/releases && ls -t | tail -n +6 | xargs -r sudo rm -rf
          
          # Cleanup deployment package
          rm /tmp/deployment.tar.gz
          
          # Reload Nginx
          sudo systemctl reload nginx
        ENDSSH
        
        rm deploy_key
