name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  serviceworkertest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.9.0
      uses: actions/setup-node@v4

    - name: install dependencies
      run: npm install

    - name: install puppeteer dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y \
            wget \
            ca-certificates \
            fonts-liberation \
            libappindicator3-1 \
            libasound2 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libdbus-1-3 \
            libgdk-pixbuf2.0-0 \
            libnspr4 \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2

    - name: Start app and run tests
      run: |
        npx http-server -p 8082 &
        npx wait-on http://127.0.0.1:8082
        npx jest ./ui.test.js --runInBand