name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  uitest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.9.0
      uses: actions/setup-node@v4

    - name: install dependencies
      run: npm install

    - name: Start app and run tests
      run: |
        npx http-server -p 8082 &
        npx wait-on http://127.0.0.1:8082
        npx jest ./ui.test.js